/**
 * Phase 30 — Autonomous AI Marketing Operating System
 *
 * Core AI infrastructure: observation, reasoning, decision making, learning, memory.
 * Integrates all existing intelligence engines into autonomous system.
 * Every decision is explainable, reversible, and respects user permissions.
 *
 * Tables:
 *   1. ai_observations          — Detected anomalies and changes
 *   2. ai_reasoning_chains      — Root cause analysis results
 *   3. ai_strategies            — Generated strategic options
 *   4. ai_recommendations       — AI-generated recommendations
 *   5. ai_playbooks             — Reusable automation templates
 *   6. ai_playbook_executions   — Execution history of playbooks
 *   7. ai_decisions             — Historical decisions and outcomes
 *   8. ai_memory_events         — Long-term memory of important events
 *   9. ai_knowledge_graph       — Entity relationships and context
 *  10. ai_simulations           — Digital twin simulation results
 *  11. ai_learning_feedback     — Learn from recommendations
 *  12. ai_briefings             — Daily/weekly/monthly AI briefings
 *  13. ai_metrics               — Track AI performance (accuracy, latency, cost)
 *  14. ai_approval_queue        — Pending approvals for autonomous actions
 */

const db = require('./database');
const { ensureMigrationsTable, isMigrationApplied, markMigrationApplied } = require('./migrationTracker');

const MIGRATION_NAME = 'phase30_autonomous_ai_marketing_os';

const SCHEMA_SQL = `

-- ─────────────────────────────────────────────
-- TABLE: ai_observations
-- Real-time anomalies and performance changes detected by AI
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_observations (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  entity_type           TEXT NOT NULL CHECK(entity_type IN (
    'campaign','ad_set','ad','creative','audience','placement',
    'account','objective','conversion','budget'
  )),
  entity_id             TEXT NOT NULL,
  observation_type      TEXT NOT NULL CHECK(observation_type IN (
    'performance_change','budget_waste','creative_fatigue','audience_fatigue',
    'auction_instability','conversion_drop','ctr_drop','cpm_spike',
    'frequency_issue','learning_limited','policy_problem','rejected_ads',
    'tracking_failure','pixel_anomaly','conversion_api_failure'
  )),
  severity              TEXT NOT NULL CHECK(severity IN ('low','medium','high','critical')),
  metric_name           TEXT,
  metric_value          REAL,
  expected_value        REAL,
  variance_percent      REAL,
  evidence_json         TEXT,
  confidence            REAL,
  is_actionable         INTEGER DEFAULT 1,
  status                TEXT DEFAULT 'detected' CHECK(status IN ('detected','investigating','resolved','false_positive')),
  created_at            TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_observations_tenant
  ON ai_observations(tenant_id);

CREATE INDEX IF NOT EXISTS idx_ai_observations_entity
  ON ai_observations(entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_ai_observations_severity
  ON ai_observations(severity);

-- ─────────────────────────────────────────────
-- TABLE: ai_reasoning_chains
-- Root cause analysis for each observation
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_reasoning_chains (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  observation_id        TEXT NOT NULL REFERENCES ai_observations(id),
  primary_cause         TEXT NOT NULL,
  secondary_causes_json TEXT,
  confidence            REAL NOT NULL,
  evidence_json         TEXT NOT NULL,
  alternative_hypotheses_json TEXT,
  risk_level            TEXT CHECK(risk_level IN ('low','medium','high','critical')),
  business_impact       TEXT,
  reasoning_steps_json  TEXT,
  created_at            TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_reasoning_chains_tenant
  ON ai_reasoning_chains(tenant_id);

CREATE INDEX IF NOT EXISTS idx_ai_reasoning_chains_observation
  ON ai_reasoning_chains(observation_id);

-- ─────────────────────────────────────────────
-- TABLE: ai_strategies
-- Multiple strategic options generated by AI
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_strategies (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  reasoning_chain_id    TEXT NOT NULL REFERENCES ai_reasoning_chains(id),
  strategy_name         TEXT NOT NULL,
  description           TEXT NOT NULL,
  expected_outcome      TEXT NOT NULL,
  expected_roi_percent  REAL,
  confidence            REAL NOT NULL,
  risk_level            TEXT CHECK(risk_level IN ('low','medium','high','critical')),
  cost_estimate         REAL,
  implementation_steps_json TEXT,
  ranking               INTEGER,
  created_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_strategies_tenant
  ON ai_strategies(tenant_id);

CREATE INDEX IF NOT EXISTS idx_ai_strategies_reasoning
  ON ai_strategies(reasoning_chain_id);

-- ─────────────────────────────────────────────
-- TABLE: ai_recommendations
-- Final AI recommendations with full reasoning
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_recommendations (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  observation_id        TEXT REFERENCES ai_observations(id),
  reasoning_chain_id    TEXT REFERENCES ai_reasoning_chains(id),
  entity_type           TEXT NOT NULL,
  entity_id             TEXT NOT NULL,
  action_type           TEXT NOT NULL CHECK(action_type IN (
    'pause','resume','budget_increase','budget_decrease','budget_shift',
    'creative_duplicate','creative_pause','audience_expand','audience_narrow',
    'placement_add','placement_remove','bid_adjust','objective_change'
  )),
  action_details_json   TEXT NOT NULL,
  reason                TEXT NOT NULL,
  evidence_json         TEXT NOT NULL,
  expected_roi_percent  REAL,
  confidence            REAL NOT NULL,
  rollback_plan         TEXT,
  approval_requirement  TEXT CHECK(approval_requirement IN ('none','manager','director','executive')),
  status                TEXT NOT NULL DEFAULT 'pending' CHECK(status IN (
    'pending','approved','rejected','executed','failed','reverted'
  )),
  execution_date        TEXT,
  result_json           TEXT,
  created_at            TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_recommendations_tenant
  ON ai_recommendations(tenant_id);

CREATE INDEX IF NOT EXISTS idx_ai_recommendations_status
  ON ai_recommendations(status);

-- ─────────────────────────────────────────────
-- TABLE: ai_playbooks
-- Reusable automation templates
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_playbooks (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  playbook_name         TEXT NOT NULL,
  playbook_type         TEXT NOT NULL CHECK(playbook_type IN (
    'low_ctr_recovery','creative_rotation','budget_scaling','audience_expansion',
    'weekend_optimization','lead_cost_recovery','messenger_optimization',
    'whatsapp_optimization','instagram_optimization','sales_recovery','custom'
  )),
  description           TEXT,
  trigger_conditions_json TEXT NOT NULL,
  actions_json          TEXT NOT NULL,
  expected_outcome      TEXT,
  is_active             INTEGER DEFAULT 1,
  approval_mode         TEXT CHECK(approval_mode IN ('none','automatic','semi_automatic','manual')),
  created_at            TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_playbooks_tenant
  ON ai_playbooks(tenant_id);

-- ─────────────────────────────────────────────
-- TABLE: ai_playbook_executions
-- Track when playbooks are executed
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_playbook_executions (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  playbook_id           TEXT NOT NULL REFERENCES ai_playbooks(id),
  entity_type           TEXT NOT NULL,
  entity_id             TEXT NOT NULL,
  status                TEXT CHECK(status IN ('pending','approved','executing','completed','failed','reverted')),
  actions_executed_json TEXT,
  results_json          TEXT,
  roi_achieved          REAL,
  created_at            TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_playbook_executions_tenant
  ON ai_playbook_executions(tenant_id);

-- ─────────────────────────────────────────────
-- TABLE: ai_decisions
-- Historical log of all AI decisions and outcomes
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_decisions (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  recommendation_id     TEXT REFERENCES ai_recommendations(id),
  decision_type         TEXT NOT NULL,
  proposed_action       TEXT NOT NULL,
  confidence            REAL NOT NULL,
  was_approved          INTEGER,
  was_executed          INTEGER,
  outcome               TEXT,
  actual_roi            REAL,
  prediction_error      REAL,
  created_at            TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_decisions_tenant
  ON ai_decisions(tenant_id);

-- ─────────────────────────────────────────────
-- TABLE: ai_memory_events
-- Long-term memory of important events
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_memory_events (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  event_type            TEXT NOT NULL CHECK(event_type IN (
    'campaign_success','campaign_failure','creative_breakthrough','audience_discovery',
    'seasonal_pattern','market_change','policy_change','business_event'
  )),
  entity_type           TEXT,
  entity_id             TEXT,
  description           TEXT NOT NULL,
  context_json          TEXT,
  learning_points_json  TEXT,
  applicable_patterns_json TEXT,
  created_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_memory_events_tenant
  ON ai_memory_events(tenant_id);

CREATE INDEX IF NOT EXISTS idx_ai_memory_events_type
  ON ai_memory_events(event_type);

-- ─────────────────────────────────────────────
-- TABLE: ai_knowledge_graph
-- Relationships between campaigns, creatives, audiences, etc.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_knowledge_graph (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  entity1_type          TEXT NOT NULL,
  entity1_id            TEXT NOT NULL,
  entity2_type          TEXT NOT NULL,
  entity2_id            TEXT NOT NULL,
  relationship_type     TEXT NOT NULL CHECK(relationship_type IN (
    'works_with','conflicts_with','complements','learned_from','similar_to','caused'
  )),
  strength              REAL,
  context_json          TEXT,
  created_at            TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_knowledge_graph_tenant
  ON ai_knowledge_graph(tenant_id);

-- ─────────────────────────────────────────────
-- TABLE: ai_simulations
-- Digital twin simulation results
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_simulations (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  scenario_name         TEXT NOT NULL,
  scenario_type         TEXT CHECK(scenario_type IN ('best_case','expected_case','worst_case','monte_carlo')),
  entity_type           TEXT NOT NULL,
  entity_id             TEXT NOT NULL,
  simulated_changes_json TEXT NOT NULL,
  predicted_metrics_json TEXT NOT NULL,
  confidence            REAL,
  created_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_simulations_tenant
  ON ai_simulations(tenant_id);

-- ─────────────────────────────────────────────
-- TABLE: ai_learning_feedback
-- Track outcomes of recommendations to learn
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_learning_feedback (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  recommendation_id     TEXT REFERENCES ai_recommendations(id),
  feedback_type         TEXT CHECK(feedback_type IN ('accepted','rejected','ignored','executed','successful','failed')),
  roi_achieved          REAL,
  confidence_error      REAL,
  lesson_learned        TEXT,
  improvement_json      TEXT,
  created_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_learning_feedback_tenant
  ON ai_learning_feedback(tenant_id);

-- ─────────────────────────────────────────────
-- TABLE: ai_briefings
-- Daily/weekly/monthly executive briefings
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_briefings (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  briefing_type         TEXT NOT NULL CHECK(briefing_type IN ('daily','weekly','monthly')),
  briefing_date         TEXT NOT NULL,
  summary_json          TEXT NOT NULL,
  risks_json            TEXT,
  opportunities_json    TEXT,
  recommended_actions_json TEXT,
  expected_impact_json  TEXT,
  generated_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_briefings_tenant
  ON ai_briefings(tenant_id);

CREATE INDEX IF NOT EXISTS idx_ai_briefings_type
  ON ai_briefings(briefing_type);

-- ─────────────────────────────────────────────
-- TABLE: ai_metrics
-- Track AI system performance
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_metrics (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  metric_type           TEXT NOT NULL CHECK(metric_type IN (
    'latency','cost','accuracy','recommendation_acceptance','automation_success',
    'prediction_accuracy','reasoning_quality'
  )),
  metric_month          TEXT NOT NULL,
  total_count           INTEGER,
  success_count         INTEGER,
  average_value         REAL,
  created_at            TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_metrics_tenant
  ON ai_metrics(tenant_id);

-- ─────────────────────────────────────────────
-- TABLE: ai_approval_queue
-- Pending approvals for autonomous actions
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_approval_queue (
  id                    TEXT PRIMARY KEY,
  tenant_id             TEXT NOT NULL REFERENCES tenants(id),
  recommendation_id     TEXT REFERENCES ai_recommendations(id),
  approval_level        TEXT NOT NULL,
  assigned_to_user_id   TEXT REFERENCES users(id),
  status                TEXT DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected','expired')),
  reason_for_rejection  TEXT,
  reviewed_at           TEXT,
  created_at            TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_approval_queue_tenant
  ON ai_approval_queue(tenant_id);

CREATE INDEX IF NOT EXISTS idx_ai_approval_queue_status
  ON ai_approval_queue(status);

`;

function runPhase30Migrations() {
  try {
    // Ensure migration registry exists
    ensureMigrationsTable();

    // Skip if env var set
    if (process.env.SKIP_MIGRATIONS) return;

    // Check if migration already applied (idempotent)
    if (isMigrationApplied(MIGRATION_NAME)) return;

    // Run migration
    db.run(SCHEMA_SQL);

    // Mark as applied
    markMigrationApplied(MIGRATION_NAME);
    console.log('✓ Phase 30 (Autonomous AI Marketing OS) migrations applied');
  } catch (e) {
    console.error(`Phase 30 migration error: ${e.message}`);
  }
}

module.exports = {
  runPhase30Migrations,
};
